version: '3'

services:
  app:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    depends_on:
      - 'postgres2'
    ports:
      - "3000:3000"
    volumes:
        - '.:/app'
    tty: true
    stdin_open: true

  postgres2:
    image: postgres
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    ports:
      - '5433:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

volumes:
  postgres:
