default: &default
  encoding: utf8
  min_messages: warning
  adapter: postgresql

docker: &docker
  host: postgres2
  username: docker
  password: docker

development:
  <<: *default
  <<: *docker
  database: find-listings-dev

